branch-defaults:
  integrationdraft:
    environment: Ecsp-env
environment-defaults:
  Ecsp-env:
    branch: null
    repository: null
global:
  application_name: ecsp
  default_ec2_keyname: null
  default_platform: arn:aws:elasticbeanstalk:us-east-2::platform/Python 3.6 running
    on 64bit Amazon Linux/2.6.6
  default_region: us-east-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  sc: git
  workspace_type: Application
